import { Inter } from "next/font/google";
import "./globals.css";
import Particles from "./components/Particles"
import Image from "next/image"
import bgImage from "./components/bridge.jpg"

//components
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scrollbar-hide">
      <body className={inter.className}>
        <Particles />
        <Navbar className="fixed top-0 left-0" />
        {children}
      </body>
    </html>
  )
}


